---
# We need sudo for some of the Docker commands.
sudo: required

env:
  global:
  - TMPDIR=$TRAVIS_BUILD_DIR/tmp    
  # Provide a list of OSes we want to use for testing.
  #- distro: centos7
  #  init: /usr/lib/systemd/systemd
  #  run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: centos6
    init: /sbin/init
    run_opts: ""
  #- distro: fedora24
  #  init: /usr/lib/systemd/systemd
  #  run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: ubuntu1604
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  #- distro: ubuntu1404
  #  init: /sbin/init
  #  run_opts: ""
  #- distro: debian8
  #  init: /lib/systemd/systemd
  #  run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

before_install:
  # Pull container from Docker Hub.
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

