# -*- mode: ruby -*-
# vi: set ft=ruby :
# Modified from https://github.com/geerlingguy/ansible-role-test-vms/blob/master/Vagrantfile

VAGRANTFILE_API_VERSION = "2"

# Uncomment when explicitly testing VirtualBox.
PROVIDER_UNDER_TEST = "virtualbox"
NETWORK_PRIVATE_IP_PREFIX = "172.16.3."

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false

  # VirtualBox.
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 3
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # VMware Fusion.
  config.vm.provider :vmware_fusion do |v, override|
    v.vmx["memsize"] = 1024
    v.vmx["numvcpus"] = 3
  end

  ###########################################################################
  # Ubuntu 16.04 - Xenial Xerus
  config.vm.define "ubuntu1604" do |ubuntu1604|
    ubuntu1604.vm.hostname = "ubuntu1604test"
    ubuntu1604.vm.box = "geerlingguy/ubuntu1604"
    ubuntu1604.vm.network :private_network, ip: NETWORK_PRIVATE_IP_PREFIX + "2"

    # Ansible.
    ubuntu1604.vm.provision "ansible" do |ansible|
      ansible.playbook = "test-jdk8-ubuntu1604.yml"
      ansible.verbose = "v"
    end
  end

  ###########################################################################
  # CentOS 6
  config.vm.define "centos6" do |centos6|
    centos6.vm.hostname = "centos6test"
    centos6.vm.box = "geerlingguy/centos6"
    centos6.vm.network :private_network, ip: NETWORK_PRIVATE_IP_PREFIX + "4"

    # Ansible.
    centos6.vm.provision "ansible" do |ansible|
      ansible.playbook = "test-jdk8-centos6.yml"
      ansible.verbose = "v"
    end
  end

  ###########################################################################    
end
